### ISSUE TITLE
Snow doesn't melt under trees.

### ISSUE THREAD

**Issue by frankchm** [IMB11/SnowUnderTrees#7]
While not an issue with the original intent of this mod, I feel like it's a branch that should probably be addressed by the mod. When this mod is used with a seasons mod, the snow doesn't melt under trees after the season changed to spring/summer. Thus, you get lingering snow piles under trees. Would you consider adding this small update?

**Comment by IMB11** [comment]
It's difficult because the current Season mods are only on 1.20.1, its easier to add support for mods which are on all 1.20.x versions, which they are not.

**Comment by VitaminJake** [comment]
I understand that Fabric Seasons is only 1.20.1 and lower but if there's a possibility of fixing this, even if it requires some extra effort, I'm extremely interested in pursuing it. Otherwise I can't have this mod in my modpack. Would be willing to help code if you teach me what I'm looking for or pay for your time fixing this. Reach out if we can work on this.

**Comment by IMB11** [comment]
No sorry, until Fabric seasons is at least on 1.20.1 to 1.20.6, I will not be adding compatibility.

**Comment by IMB11** [comment]
I'll have a look at it

**Comment by IMB11** [comment]
Yup, i'll take a look :+1:

**Comment by IMB11** [comment]
Serene seasons support has been added in 2.5.0

@jamieclipse 
@VitaminJake 
@frankchm
